FROM mcr.microsoft.com/devcontainers/base:alpine-3.16

# [Optional] Uncomment this section to install additional OS packages.
RUN apk update \
    && apk upgrade \
    && apk add --no-cache sudo bash openjdk-17-jdk
